-- =====================================================================
-- Nova (esclationsys) — Recommended Row Level Security (RLS) policies
-- =====================================================================
-- WHY THIS FILE EXISTS
-- This project has no custom backend: the browser talks to Supabase
-- directly using the public "anon" key (which is meant to be public —
-- that is not a leak). Every "Admin"/"team_leader only"/"own data only"
-- rule enforced in app.js (isAdmin, adminRole, canDelete(), etc.) is
-- UI-ONLY. Anyone with the anon key (i.e. anyone who opens the site)
-- can call the Supabase REST API directly from the browser console and
-- skip the UI entirely. The ONLY real enforcement layer is Postgres
-- Row Level Security on each table. This file was generated by
-- reading app.js end-to-end and matching every sb.from(...) call to
-- the access rule the UI already assumes.
--
-- HOW TO APPLY
-- Run this in the Supabase project's SQL Editor (Dashboard → SQL
-- Editor → New query → paste → Run). It is written to be safe to
-- re-run (DROP POLICY IF EXISTS before each CREATE POLICY).
-- Review it first — table/column names below are inferred from the
-- client code and must match your actual schema exactly, or the
-- statements will fail loudly (they will NOT silently apply to the
-- wrong table).
--
-- This file does not touch any data. It only adds access-control
-- rules. Nothing here drops a table, column, or row.
-- =====================================================================


-- ---------------------------------------------------------------------
-- Helper functions (SECURITY DEFINER so they can read `profiles`
-- without recursively re-triggering RLS on `profiles` itself)
-- ---------------------------------------------------------------------
create or replace function public.current_role_name()
returns text
language sql
security definer
set search_path = public
stable
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_admin_or_lead()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select coalesce(public.current_role_name() in ('admin', 'team_leader'), false);
$$;

create or replace function public.is_full_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select coalesce(public.current_role_name() = 'admin', false);
$$;


-- ---------------------------------------------------------------------
-- profiles — each user reads only their own role. No client-side
-- INSERT/UPDATE/DELETE at all: role changes must be made by an admin
-- directly in the Supabase dashboard, never through the app. Without
-- this, a user could otherwise grant themselves 'admin' by editing
-- their own profile row.
-- ---------------------------------------------------------------------
alter table public.profiles enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
  for select using (auth.uid() = id);


-- ---------------------------------------------------------------------
-- Content tables: categories, scripts, general_info, critical_items,
-- etiquette_items — readable by any signed-in employee, writable only
-- by admin/team_leader, deletable only by full admin (matches the
-- app's "limited admin = add/edit, no delete" model).
-- ---------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array['categories','scripts','general_info','critical_items','etiquette_items'] loop
    execute format('alter table public.%I enable row level security;', t);

    execute format('drop policy if exists "%s_select_authenticated" on public.%I;', t, t);
    execute format(
      'create policy "%s_select_authenticated" on public.%I for select using (auth.role() = ''authenticated'');',
      t, t
    );

    execute format('drop policy if exists "%s_insert_admin" on public.%I;', t, t);
    execute format(
      'create policy "%s_insert_admin" on public.%I for insert with check (public.is_admin_or_lead());',
      t, t
    );

    execute format('drop policy if exists "%s_update_admin" on public.%I;', t, t);
    execute format(
      'create policy "%s_update_admin" on public.%I for update using (public.is_admin_or_lead()) with check (public.is_admin_or_lead());',
      t, t
    );

    execute format('drop policy if exists "%s_delete_full_admin" on public.%I;', t, t);
    execute format(
      'create policy "%s_delete_full_admin" on public.%I for delete using (public.is_full_admin());',
      t, t
    );
  end loop;
end $$;


-- ---------------------------------------------------------------------
-- updates (the "New Updates" feed) — same read-all/write-admin shape.
-- ---------------------------------------------------------------------
alter table public.updates enable row level security;

drop policy if exists "updates_select_authenticated" on public.updates;
create policy "updates_select_authenticated" on public.updates
  for select using (auth.role() = 'authenticated');

drop policy if exists "updates_insert_admin" on public.updates;
create policy "updates_insert_admin" on public.updates
  for insert with check (public.is_admin_or_lead());

drop policy if exists "updates_delete_full_admin" on public.updates;
create policy "updates_delete_full_admin" on public.updates
  for delete using (public.is_full_admin());


-- ---------------------------------------------------------------------
-- suggestions — any employee can submit one (their own email only,
-- matching name = currentUserEmail in app.js). Only admin/team_leader
-- can read the list (app.js already only fetches this when isAdmin,
-- but that fetch call is not a real restriction without this policy).
-- Only a full admin can delete.
-- ---------------------------------------------------------------------
alter table public.suggestions enable row level security;

drop policy if exists "suggestions_insert_own_email" on public.suggestions;
create policy "suggestions_insert_own_email" on public.suggestions
  for insert with check (
    auth.role() = 'authenticated'
    and name = (auth.jwt() ->> 'email')
  );

drop policy if exists "suggestions_select_admin" on public.suggestions;
create policy "suggestions_select_admin" on public.suggestions
  for select using (public.is_admin_or_lead());

drop policy if exists "suggestions_delete_full_admin" on public.suggestions;
create policy "suggestions_delete_full_admin" on public.suggestions
  for delete using (public.is_full_admin());


-- ---------------------------------------------------------------------
-- technical_issues — shared log, every employee can read it (by
-- design — see the comment in app.js). Insert is only allowed under
-- the reporting employee's own verified email, so nobody can log an
-- issue in a colleague's name. Delete is full-admin only.
-- ---------------------------------------------------------------------
alter table public.technical_issues enable row level security;

drop policy if exists "technical_issues_select_authenticated" on public.technical_issues;
create policy "technical_issues_select_authenticated" on public.technical_issues
  for select using (auth.role() = 'authenticated');

drop policy if exists "technical_issues_insert_own_email" on public.technical_issues;
create policy "technical_issues_insert_own_email" on public.technical_issues
  for insert with check (
    auth.role() = 'authenticated'
    and employee_email = (auth.jwt() ->> 'email')
  );

drop policy if exists "technical_issues_delete_full_admin" on public.technical_issues;
create policy "technical_issues_delete_full_admin" on public.technical_issues
  for delete using (public.is_full_admin());


-- ---------------------------------------------------------------------
-- user_presence — each user may only write their own heartbeat row
-- (so nobody can spoof a colleague's online status). Reading the full
-- presence list is admin-only, matching the app's admin-only presence
-- panel; every user may still read their own row.
-- ---------------------------------------------------------------------
alter table public.user_presence enable row level security;

drop policy if exists "user_presence_select_admin_or_own" on public.user_presence;
create policy "user_presence_select_admin_or_own" on public.user_presence
  for select using (public.is_admin_or_lead() or user_id = auth.uid());

drop policy if exists "user_presence_upsert_own" on public.user_presence;
create policy "user_presence_upsert_own" on public.user_presence
  for insert with check (user_id = auth.uid());

drop policy if exists "user_presence_update_own" on public.user_presence;
create policy "user_presence_update_own" on public.user_presence
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());


-- ---------------------------------------------------------------------
-- training_problems / training_nodes — regular employees only see
-- PUBLISHED (is_active = true) content; admin/team_leader see drafts
-- too (needed for the Training Builder). Write access is admin-only,
-- delete is full-admin only. This is the one the client code openly
-- relies on RLS for: app.js fetches every row unconditionally and
-- expects the database to hide drafts from non-admins.
-- ---------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array['training_problems','training_nodes'] loop
    execute format('alter table public.%I enable row level security;', t);

    execute format('drop policy if exists "%s_select_visible" on public.%I;', t, t);
    execute format(
      'create policy "%s_select_visible" on public.%I for select using (is_active = true or public.is_admin_or_lead());',
      t, t
    );

    execute format('drop policy if exists "%s_insert_admin" on public.%I;', t, t);
    execute format(
      'create policy "%s_insert_admin" on public.%I for insert with check (public.is_admin_or_lead());',
      t, t
    );

    execute format('drop policy if exists "%s_update_admin" on public.%I;', t, t);
    execute format(
      'create policy "%s_update_admin" on public.%I for update using (public.is_admin_or_lead()) with check (public.is_admin_or_lead());',
      t, t
    );

    execute format('drop policy if exists "%s_delete_full_admin" on public.%I;', t, t);
    execute format(
      'create policy "%s_delete_full_admin" on public.%I for delete using (public.is_full_admin());',
      t, t
    );
  end loop;
end $$;

-- training_options has no is_active column of its own — it belongs to
-- a training_node, so visibility follows the parent node's is_active.
alter table public.training_options enable row level security;

drop policy if exists "training_options_select_visible" on public.training_options;
create policy "training_options_select_visible" on public.training_options
  for select using (
    public.is_admin_or_lead()
    or exists (
      select 1 from public.training_nodes n
      where n.id = training_options.node_id and n.is_active = true
    )
  );

drop policy if exists "training_options_insert_admin" on public.training_options;
create policy "training_options_insert_admin" on public.training_options
  for insert with check (public.is_admin_or_lead());

drop policy if exists "training_options_update_admin" on public.training_options;
create policy "training_options_update_admin" on public.training_options
  for update using (public.is_admin_or_lead()) with check (public.is_admin_or_lead());

drop policy if exists "training_options_delete_full_admin" on public.training_options;
create policy "training_options_delete_full_admin" on public.training_options
  for delete using (public.is_full_admin());


-- =====================================================================
-- AFTER YOU RUN THIS
-- 1. Log in to the app as an 'agent'/'quality' account and confirm:
--    scripts/training/tech-issue log still load normally, the Admin
--    Portal stays inaccessible, and no console errors appear.
-- 2. Log in as 'team_leader' and confirm you can add/edit content but
--    delete buttons still fail (as the UI already hides them for you,
--    but now the API blocks it too if called directly).
-- 3. Log in as 'admin' and confirm full CRUD still works everywhere.
-- 4. If any table name or column name above doesn't match your real
--    schema, that CREATE POLICY statement will error — fix the name
--    and re-run just that block.
-- =====================================================================
